In [99]:
import pandas as pd
df = pd.read_csv('C:/Users/tiger/Downloads/musinsa_recommendation_system/데이터_전처리_완료.csv'); df

상품명     카테고리  \
0                          에센셜 텐셀 린넨 셔츠 - 9 COLOR   셔츠 블라우스   
1              2PACK SMALL ARCH TEE WHITE / BLACK   반소매 티셔츠   
2                                   pearl t-shirt   반소매 티셔츠   
3     컷 헤비 피그먼트 티셔츠-차콜- cut-heavy PIGMENT tshirts   반소매 티셔츠   
4                         케이블 라운드 하프 니트 - 6 COLOR   반소매 티셔츠   
..                                             ...      ...   
919                     쿨 썸머 에센셜 라운드 반팔 니트티 BLACK    니트 스웨터   
920                   Do Cats Feel Love Tee White   반소매 티셔츠   
921                                  컴프레션 긴팔 티셔츠         상의   
922       디미트리 호놀룰루 반팔 셔츠 DIMITRI HONOLULU SHIRTS   셔츠 블라우스   
923    유니섹스 고스트 프린팅 자수 오버핏 반팔티 고스트 프린팅 자수 오버핏 반팔티   반소매 티셔츠   

                         브랜드  성별   평점    리뷰수  \
0                      SUARE   남  4.8   2196   
1                       YALE  공용  4.8  14852   
2                   ODDPEARL  공용  4.9   2169   
3                  SOVERMENT   남  4.9   7912   
4                      SUARE   남  4.9   2933   
..                       ...  ..  ...    ...   
919                  KNITTED  공용  4.8   1014   
920                   FASTLE  공용  4.7    292   
921  MUSINSA STANDARD SPORTS   남  4.8    718   
922            DIMITRI BLACK   남  5.0     85   
923                 DOMINANT  공용  4.9   1361   

                                                    태그  좋아요 수     조회수    구매수  \
0         린넨 셔츠 린넨셔츠 긴팔셔츠 기본셔츠 베이직셔츠 오버핏셔츠 23S/S 셔츠컬렉션  22270  124000  18000   
1       반팔티 여름반팔티 남자반팔티 반팔티셔츠 원마일웨어 패키지/셋업 레인 장마 액티브웨어  71139  181000  63000   
2                    반팔 반팔티 반팔티셔츠 로고티셔츠 티셔츠 그래픽티셔츠 오버핏  21713  117000  16000   
3                   피그먼트 반팔 반팔티 티셔츠 오버핏 무지 깡스타일리스트PICK  39349  125000  34000   
4          반팔 반팔니트 반팔티 티셔츠 여름니트 니트 니트컬렉션 23SUMMER 서머니트  15622   83000  16000   
..                                                 ...    ...     ...    ...   
919                     반팔티 니트 반팔 여름니트 반팔니트 남자니트 니트컬렉션   3667    8300   1000   
920                               반팔티 반팔 반팔티셔츠 티셔츠 아울렛  12764    7300   1000   
921   기능성 애슬레저 무신사스탠다드퍼포먼스 무신사스탠다드스포츠 퍼포먼스 스포츠웨어 PL...   1775    2700   1800   
922          하와이안 하와이안셔츠 남자반팔셔츠 오픈카라셔츠 여름셋업 남자셔츠 셔츠컬렉션   1074   11000    350   
923     그래픽티셔츠 로고티셔츠 반팔티 오버핏 그래픽 오버핏반팔 깡스타일리스트PICK 락시크   9396    8500   1400   

     인기 나이 인기 성별     가격                                                 리뷰  
0       29     남  30198  소매가 넓은 편이라 팔을 접어도 고정이 쉽게 안되더라고요 제 전완근의 문제라 생각하...  
1       24     남  26520  무난무난하게 입기 좋은 티고 아무 바지나 매칭해도 잘 어울려요 구겨짐이 좀 있지만 ...  
2       29     남  30511  여름에 편하게 입기 좋은 무난템입니다. 사이즈는 정사이즈로 넉넉하게 잘 맞아요. 탄...  
3       24     남  36600  재질이 탄탄한 편이라 핏 예쁘게 잡혀요 기장 매우 긴편이라 팔 접고 넣입이 이쁨 리...  
4       24     남  25093  워셔블이긴 한데 조심스럽게 인스트럭션대로 세탁해도 약간 줄어듭니다 꽈배기 패턴이 마...  
..     ...   ...    ...                                                ...  
919     29     남  39200  처음 받았을때는 너무 하늘거려서 별로인가 싶었는데 몇번 입어보니 편한 일상복? 느낌...  
920     21     여  25200  좋아요 평소에 편안하게 입기 좋은 것 같아요 손이 가는 스타일. S사이즈 주문해서 ...  
921     24     남  25090  사이즈 딱 맞네요 가게에서 입으려고 삿습니다 시원하고 좋아요 타이트해서 좋네요 사이...  
922     31     남  42900  착용감좋고 가볍고 야들야들해서 여름에 자주입겠어요. 포장지가 다 찢겨져왔습니다ㅠㅠ ...  
923     24     남  34095  프린팅이 예뻐서 너무 마음에 들어요 조금 두꺼운데 좋습니다 목걸이나 그런거 같이 매...  

[924 rows x 14 columns]

In [100]:
from sklearn.feature_extraction.text import TfidfVectorizer
from sklearn.metrics.pairwise import cosine_similarity
import numpy as np

text_columns = ['태그', '카테고리', '리뷰']

for col in text_columns:
    print(col,"유사도")
    tfidf = TfidfVectorizer(min_df=1, ngram_range=(1, 3))
    matrix = tfidf.fit_transform(df[col])
    cos_sim = cosine_similarity(matrix, matrix)
    print(cos_sim[5:16, 5:16]) # 행렬의 특정 행/열만 출력
    print("\n")

태그 유사도
[[1.         0.09803669 0.         0.         0.00561806 0.
  0.         0.00581454 0.00430107 0.00479434 0.08914684]
 [0.09803669 1.         0.         0.         0.         0.
  0.         0.         0.         0.         0.06198566]
 [0.         0.         1.         0.         0.01148113 0.03729537
  0.         0.0279591  0.01602692 0.         0.        ]
 [0.         0.         0.         1.         0.         0.
  0.         0.         0.         0.         0.        ]
 [0.00561806 0.         0.01148113 0.         1.         0.05289164
  0.         0.03271109 0.0133901  0.01406755 0.0074398 ]
 [0.         0.         0.03729537 0.         0.05289164 1.
  0.         0.02954289 0.04674648 0.         0.        ]
 [0.         0.         0.         0.         0.         0.
  1.         0.         0.         0.         0.        ]
 [0.00581454 0.         0.0279591  0.         0.03271109 0.02954289
  0.         1.         0.0117283  0.01455952 0.02117956]
 [0.00430107 0.         0

In [101]:
def tfidf_cos_sim(col):
    tfidf = TfidfVectorizer(min_df=1, ngram_range=(1, 3))
    matrix = tfidf.fit_transform(df[col])
    cos_sim = cosine_similarity(matrix, matrix)
    print(cos_sim)
    return cos_sim

tag = tfidf_cos_sim('태그')
category = tfidf_cos_sim('카테고리')
review = tfidf_cos_sim('리뷰')
brand = tfidf_cos_sim('브랜드')

[[1.         0.         0.         ... 0.         0.02201777 0.        ]
 [0.         1.         0.01297691 ... 0.         0.         0.0042833 ]
 [0.         0.01297691 1.         ... 0.         0.         0.05185592]
 ...
 [0.         0.         0.         ... 1.         0.         0.        ]
 [0.02201777 0.         0.         ... 0.         1.         0.        ]
 [0.         0.0042833  0.05185592 ... 0.         0.         1.        ]]
[[1. 0. 0. ... 0. 1. 0.]
 [0. 1. 1. ... 0. 0. 1.]
 [0. 1. 1. ... 0. 0. 1.]
 ...
 [0. 0. 0. ... 1. 0. 0.]
 [1. 0. 0. ... 0. 1. 0.]
 [0. 1. 1. ... 0. 0. 1.]]
[[1.         0.00601768 0.00863414 ... 0.00529198 0.0039763  0.00638243]
 [0.00601768 1.         0.0143744  ... 0.0083879  0.00579577 0.00484644]
 [0.00863414 0.0143744  1.         ... 0.01128465 0.00794463 0.00840551]
 ...
 [0.00529198 0.0083879  0.01128465 ... 1.         0.00434917 0.00443031]
 [0.0039763  0.00579577 0.00794463 ... 0.00434917 1.         0.00938688]
 [0.00638243 0.00484644 0.0084

In [102]:
total_sim = ( review * 0.1 + category * 1 + tag * 1 )
            #+ np.repeat(np.repeat([df['평점'].values], len(df['평점']) , axis=0) * 0.001
            #+ np.repeat(np.repeat([df['조회수'].values], len(df['조회수']) , axis=0) * 0.001
            #+ np.repeat(np.repeat([df['구매수'].values], len(df['구매수']) , axis=0) * 0.001 )

total_sim_sorted_ind = total_sim.argsort()[:, ::-1] 

def find_sim_item(df, sorted_ind, item_name, top_n):
    # 입력된 item_name을 포함하는 이름을 가진 아이템을 데이터 프레임에서 찾기
    item_name_df = df[df['상품명'].str.contains(item_name, case=False, na=False)]
    
    # 아이템의 첫 번째 인덱스 값을 item_index에 저장
    item_index = item_name_df.index.values[0] # 첫 번째 인덱스만 사용

    # sorted_ind에서 해당 아이템과 가장 유사한 상품들의 인덱스 추출
    similar_indexes = sorted_ind[item_index, :top_n]
    return df.iloc[similar_indexes]

find_sim_item(df, total_sim_sorted_ind, '컴프레션 긴팔 티셔츠', 10) 

상품명 카테고리  \
921                                      컴프레션 긴팔 티셔츠     상의   
681                                      컴프레션 반팔 티셔츠     상의   
217                                 올라운드 트레이닝 반팔 티셔츠     상의   
275                                올라운드 트레이닝 슬리브리스 탑     상의   
608   애슬레틱 오버핏 숏 슬리브 3 color Athletic Overfit Short...   상의   
95                              메인 스몰 로고 에어 머슬핏 숏 슬리브    상의   
774                       8/8 배송  BLOCK 메쉬 오버핏 반팔 티셔츠    상의   
392                                      스탠다드 머슬핏 반팔티    상의   
222                                      메인로고 머슬핏 반팔티    상의   
387                           에어쿨링 드라이 기능성 반팔티+반바지 세트    상의   

                         브랜드 성별   평점   리뷰수  \
921  MUSINSA STANDARD SPORTS  남  4.8   718   
681  MUSINSA STANDARD SPORTS  남  4.8  1245   
217  MUSINSA STANDARD SPORTS  남  4.9  5082   
275  MUSINSA STANDARD SPORTS  남  4.9  3004   
608                     HDEX  남  4.9   235   
95                      HDEX  남  4.9   659   
774             MUSCLE ARMED  남  4.9    98   
392                     HDEX  남  4.8   812   
222                     HDEX  남  4.9  1531   
387                  GLIMMER  남  4.8   191   

                                                    태그  좋아요 수    조회수   구매수  \
921   기능성 애슬레저 무신사스탠다드퍼포먼스 무신사스탠다드스포츠 퍼포먼스 스포츠웨어 PL...   1775   2700  1800   
681   기능성 애슬레저 무신사스탠다드퍼포먼스 무신사스탠다드스포츠 퍼포먼스 스포츠 스포츠웨...   4019   7500  3100   
217   기능성 트레이닝 운동복 기능성티 반팔티 스포츠웨어 PLUS배송 플러스배송 빠른배송...   6361  13000  6900   
275   기능성 트레이닝 운동복 나시 기능성티 무신사스탠다드퍼포먼스 무신사스탠다드스포츠 P...   3761  10000  3400   
608                     반팔티 반팔 스포츠웨어 반팔티셔츠 오버핏 23SS컬렉션    627  10000  1100   
95         스포츠웨어 반팔티 반팔 반팔티셔츠 피트니스웨어 머슬핏 2PACK 패키지 짐웨어   2277  18000  3100   
774                짐웨어 메쉬티셔츠 메쉬티 스포츠웨어 운동복상의 운동복 운동티셔츠    671  12000   500   
392             머슬핏 반팔 라운드티 반팔티 스포츠웨어 짐웨어 2PACK 패키지 무지   4128  19000  4300   
222   반팔티셔츠 운동복 반팔티 머슬핏반팔티 기능성티셔츠 머슬핏 스포츠웨어 2PACK 메...   4376  46000  6200   
387                       기능성반팔 반팔 반팔티셔츠 세트 운동복 홈트 패키지   1854  12000  2100   

     인기 나이 인기 성별     가격                                                 리뷰  
921     24     남  25090  사이즈 딱 맞네요 가게에서 입으려고 삿습니다 시원하고 좋아요 타이트해서 좋네요 사이...  
681     24     남  21490  몸좋아보이고 너무 좋습니다. 배송도빠르고 다음에 또 구매예정 179/74 일반체형 ...  
217     29     남  21490  딱 기본 티셔츠입니다. 휘뚜루 마뚜루 입기 너무좋아요 어깨부분이 살짝 작아서 한치수...  
275     29     남  19690  스포츠용이어서 그런지 사이즈 조금 작습니다. 집에서 편하게 입거나 여름에 이너로 입...  
608     29     남  46000  평상시랑 운동할때 입을려고 구매했는데 재질 디자인 모두 만족합니다 ! 옷도 탄탄하고...  
95      24     남  56243  벼르고 있었는데 마침 세일해서 구매했습니다 목부분이 조금 약하고 넓은것 같은데 재질...  
774     29     남  34836  박시하고 너무 이쁩니다 매쉬소재라 엄청시원하고 좋아요 옷 너무 편하고 이뻐요!! 평...  
392     24     남  56243  일부러 맞게입으려고 작게 사긴했는데, 어깨라인이 꽤 높았는지 정면에서 봤을 때 팔소...  
222     24     남  65617  운동할때 입기 좋아요 핏도 맞고 통풍도 잘됩니다 무난해서 어디에 입든 다 잘 어울리...  
387     24     남  17700  조금 까끌까끌한 감이있는것 같다고 하는데 싼 거 생각하면 가성비 좋다고하네요 시원하...